package Vistas;

import controladores.ControladorVentanaAdministradorLaboratorio;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import src.Estudiante;
import src.Laboratorio;
import src.Persona;

public class VentanaGestionarLab extends javax.swing.JFrame {

    ControladorVentanaAdministradorLaboratorio controladorVentanaAdministradorLaboratorio;
    VentanaAdministradorLaboratorio ventanaLaboratorio;
    Laboratorio laboratorio;
    int fila, columna;

    public VentanaGestionarLab(VentanaAdministradorLaboratorio ventanaLaboratorio, int fila, int columna) {
        initComponents();
        this.controladorVentanaAdministradorLaboratorio = new ControladorVentanaAdministradorLaboratorio();
        this.ventanaLaboratorio = ventanaLaboratorio;
        this.fila = fila;
        this.columna = columna;
        this.laboratorio = controladorVentanaAdministradorLaboratorio.obtenerLaboratorio(fila, columna);
        cargarTablaEstudiante();
        cupoMaximo();
        setLocationRelativeTo(this);
        jLabelNombreEstudianteEspera.setText(estudiantesEnCola());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEstu = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtCodigoUniversitario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaEstudiantesEnLaboratorio = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelCupoMaximo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jEliminarIngreso = new javax.swing.JPanel();
        btnEliminarIngreso = new javax.swing.JLabel();
        jPrestarHerramientas = new javax.swing.JPanel();
        btnPrestarHerramientas = new javax.swing.JLabel();
        jIngresarEstudiante = new javax.swing.JPanel();
        btnIngresarEstudiante = new javax.swing.JLabel();
        jDeshabilitarLaboratorio = new javax.swing.JPanel();
        btnDeshabilitarLaboratorio = new javax.swing.JLabel();
        jVolver = new javax.swing.JPanel();
        btnVolver = new javax.swing.JLabel();
        jLabelTextEstudianteCola = new javax.swing.JLabel();
        jLabelNombreEstudianteEspera = new javax.swing.JLabel();
        jVolver1 = new javax.swing.JPanel();
        btnRetirarEstudiantes = new javax.swing.JLabel();
        jVolver2 = new javax.swing.JPanel();
        btnVolver1 = new javax.swing.JLabel();
        jVolver3 = new javax.swing.JPanel();
        btnRetirarEstudiantes1 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(TablaEstu);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtCodigoUniversitario.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtCodigoUniversitario.setForeground(new java.awt.Color(153, 153, 153));
        txtCodigoUniversitario.setText("Codigo Universitario");
        txtCodigoUniversitario.setBorder(null);
        txtCodigoUniversitario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCodigoUniversitarioMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("GESTIONAR LABORATORIO");

        TablaEstudiantesEnLaboratorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaEstudiantesEnLaboratorioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaEstudiantesEnLaboratorio);

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Estudiantes en laboratorio");

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cupo laboratorio:");

        jLabelCupoMaximo.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabelCupoMaximo.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCupoMaximo.setText("30/");

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText(" ");

        jEliminarIngreso.setBackground(new java.awt.Color(51, 102, 255));

        btnEliminarIngreso.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnEliminarIngreso.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarIngreso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminarIngreso.setText("ELIMINAR INGRESO");
        btnEliminarIngreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminarIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarIngresoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jEliminarIngresoLayout = new javax.swing.GroupLayout(jEliminarIngreso);
        jEliminarIngreso.setLayout(jEliminarIngresoLayout);
        jEliminarIngresoLayout.setHorizontalGroup(
            jEliminarIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminarIngreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jEliminarIngresoLayout.setVerticalGroup(
            jEliminarIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminarIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPrestarHerramientas.setBackground(new java.awt.Color(51, 102, 255));

        btnPrestarHerramientas.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnPrestarHerramientas.setForeground(new java.awt.Color(255, 255, 255));
        btnPrestarHerramientas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPrestarHerramientas.setText("PRESTAR HERRAMIENTAS");
        btnPrestarHerramientas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrestarHerramientas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPrestarHerramientasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPrestarHerramientasLayout = new javax.swing.GroupLayout(jPrestarHerramientas);
        jPrestarHerramientas.setLayout(jPrestarHerramientasLayout);
        jPrestarHerramientasLayout.setHorizontalGroup(
            jPrestarHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPrestarHerramientas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPrestarHerramientasLayout.setVerticalGroup(
            jPrestarHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnPrestarHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jIngresarEstudiante.setBackground(new java.awt.Color(51, 102, 255));

        btnIngresarEstudiante.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnIngresarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarEstudiante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnIngresarEstudiante.setText("REGISTRAR INGRESO");
        btnIngresarEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresarEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarEstudianteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jIngresarEstudianteLayout = new javax.swing.GroupLayout(jIngresarEstudiante);
        jIngresarEstudiante.setLayout(jIngresarEstudianteLayout);
        jIngresarEstudianteLayout.setHorizontalGroup(
            jIngresarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnIngresarEstudiante, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );
        jIngresarEstudianteLayout.setVerticalGroup(
            jIngresarEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnIngresarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jDeshabilitarLaboratorio.setBackground(new java.awt.Color(51, 102, 255));

        btnDeshabilitarLaboratorio.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnDeshabilitarLaboratorio.setForeground(new java.awt.Color(255, 255, 255));
        btnDeshabilitarLaboratorio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDeshabilitarLaboratorio.setText("DESHABILITAR LABORATORIO");
        btnDeshabilitarLaboratorio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeshabilitarLaboratorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeshabilitarLaboratorioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDeshabilitarLaboratorioLayout = new javax.swing.GroupLayout(jDeshabilitarLaboratorio);
        jDeshabilitarLaboratorio.setLayout(jDeshabilitarLaboratorioLayout);
        jDeshabilitarLaboratorioLayout.setHorizontalGroup(
            jDeshabilitarLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDeshabilitarLaboratorio)
        );
        jDeshabilitarLaboratorioLayout.setVerticalGroup(
            jDeshabilitarLaboratorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDeshabilitarLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jVolver.setBackground(new java.awt.Color(51, 102, 255));

        btnVolver.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolver.setText("VOLVER");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jVolverLayout = new javax.swing.GroupLayout(jVolver);
        jVolver.setLayout(jVolverLayout);
        jVolverLayout.setHorizontalGroup(
            jVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );
        jVolverLayout.setVerticalGroup(
            jVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jLabelTextEstudianteCola.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabelTextEstudianteCola.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTextEstudianteCola.setText("Estudiante en cola:");

        jLabelNombreEstudianteEspera.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabelNombreEstudianteEspera.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNombreEstudianteEspera.setText("Ninguno");

        jVolver1.setBackground(new java.awt.Color(51, 102, 255));

        btnRetirarEstudiantes.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnRetirarEstudiantes.setForeground(new java.awt.Color(255, 255, 255));
        btnRetirarEstudiantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRetirarEstudiantes.setText("RETIRAR ESTUDIANTES");
        btnRetirarEstudiantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRetirarEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetirarEstudiantesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jVolver1Layout = new javax.swing.GroupLayout(jVolver1);
        jVolver1.setLayout(jVolver1Layout);
        jVolver1Layout.setHorizontalGroup(
            jVolver1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRetirarEstudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jVolver1Layout.setVerticalGroup(
            jVolver1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRetirarEstudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jVolver2.setBackground(new java.awt.Color(51, 102, 255));

        btnVolver1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnVolver1.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolver1.setText("VACIAR COLA");
        btnVolver1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolver1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jVolver2Layout = new javax.swing.GroupLayout(jVolver2);
        jVolver2.setLayout(jVolver2Layout);
        jVolver2Layout.setHorizontalGroup(
            jVolver2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );
        jVolver2Layout.setVerticalGroup(
            jVolver2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jVolver3.setBackground(new java.awt.Color(51, 102, 255));

        btnRetirarEstudiantes1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnRetirarEstudiantes1.setForeground(new java.awt.Color(255, 255, 255));
        btnRetirarEstudiantes1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRetirarEstudiantes1.setText("RETIRAR HERRAMIENTAS");
        btnRetirarEstudiantes1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRetirarEstudiantes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRetirarEstudiantes1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jVolver3Layout = new javax.swing.GroupLayout(jVolver3);
        jVolver3.setLayout(jVolver3Layout);
        jVolver3Layout.setHorizontalGroup(
            jVolver3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jVolver3Layout.createSequentialGroup()
                .addComponent(btnRetirarEstudiantes1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jVolver3Layout.setVerticalGroup(
            jVolver3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRetirarEstudiantes1, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodigoUniversitario, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(jLabelCupoMaximo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jIngresarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jVolver1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPrestarHerramientas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jEliminarIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDeshabilitarLaboratorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jVolver3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTextEstudianteCola)
                        .addGap(21, 21, 21)
                        .addComponent(jLabelNombreEstudianteEspera)
                        .addGap(90, 90, 90)
                        .addComponent(jVolver2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelCupoMaximo)
                                .addComponent(jLabel5)))
                        .addGap(42, 42, 42)
                        .addComponent(txtCodigoUniversitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jIngresarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEliminarIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPrestarHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDeshabilitarLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jVolver1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jVolver3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelTextEstudianteCola)
                                    .addComponent(jLabelNombreEstudianteEspera)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jVolver2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jVolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoUniversitarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCodigoUniversitarioMousePressed
        if (txtCodigoUniversitario.getText().equals("Codigo Universitario")) {
            txtCodigoUniversitario.setText("");
            txtCodigoUniversitario.setForeground(Color.black);
        }
     }//GEN-LAST:event_txtCodigoUniversitarioMousePressed

    private void cargarTablaEstudiante() {
        DefaultTableModel model = new DefaultTableModel();
        String[] columnas = new String[]{
            "Codigo universitario", "nombre", "apellido", "cedula", "celular"
        };
        model.setColumnIdentifiers(columnas);
        for (int i = 0; i < laboratorio.getEstudiantes().getSize(); i++) {
            model.addRow(new Object[]{
                laboratorio.getEstudiantes().obtenerDatoIndice(i).getCodigoUniversitario(),
                laboratorio.getEstudiantes().obtenerDatoIndice(i).getNombre(),
                laboratorio.getEstudiantes().obtenerDatoIndice(i).getApellido(),
                laboratorio.getEstudiantes().obtenerDatoIndice(i).getCedula(),
                laboratorio.getEstudiantes().obtenerDatoIndice(i).getNumeroCelular(),});
        }

        TablaEstudiantesEnLaboratorio.setModel(model);
    }

    private void btnDeshabilitarLaboratorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeshabilitarLaboratorioMouseClicked
        if (laboratorio.getDisponibilidad().equals(Laboratorio.DISPONIBLE)) {
            if (laboratorio.getEstudiantes().getSize() == 0) {
                String motivo = JOptionPane.showInputDialog(null, "Escriba el motivo por el cual deshabilitara el labatorio");
                laboratorio.setMotivo(motivo);
                controladorVentanaAdministradorLaboratorio.deshabilitarLaboratorio(fila, columna);
                JOptionPane.showMessageDialog(null, "Laboratorio deshabilitado correctamente.");
                ventanaLaboratorio.setVisible(true);
                this.dispose();
                ventanaLaboratorio.validarPosiciones();
            } else {
                JOptionPane.showMessageDialog(null, "El laboratorio no se puede deshabilitar ya que hay un estudiante dentro.");
            }
        }
    }//GEN-LAST:event_btnDeshabilitarLaboratorioMouseClicked

    private String cupoLaboratorio() {
        int contador = 0;
        for (int i = 0; i < laboratorio.getEstudiantes().getSize(); i++) {
            contador = i + 1;
        }
        return String.valueOf(contador);
    }

    private void btnIngresarEstudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarEstudianteMouseClicked
        String codigoUniversitario = txtCodigoUniversitario.getText();
        Persona persona = controladorVentanaAdministradorLaboratorio.buscarPersonaCodigo(codigoUniversitario);
        if (persona instanceof Estudiante) {
            Estudiante estudiante = (Estudiante) persona;
            if (controladorVentanaAdministradorLaboratorio.obtenerLaboratorio(fila, columna).buscarEstudianteTodosLosLaboratorios(estudiante.getCodigoUniversitario()) == null) {
                if (controladorVentanaAdministradorLaboratorio.obtenerLaboratorio(fila, columna).getCupo() == controladorVentanaAdministradorLaboratorio.obtenerLaboratorio(fila, columna).getEstudiantes().getSize()) {
                    JOptionPane.showMessageDialog(null, "El laboratorio se encuentra lleno, por lo cual el estudiante: " + estudiante.getNombre() + " pasara a la cola de espera.");
                    controladorVentanaAdministradorLaboratorio.registrarColaLaboraorio(fila, columna, estudiante);
                    jLabelNombreEstudianteEspera.setText(estudiantesEnCola());
                } else {
                    controladorVentanaAdministradorLaboratorio.regLab(fila, columna, estudiante);
                }
            } else {
                JOptionPane.showMessageDialog(null, "El estudiante: " + estudiante.getNombre() + " ya se encuentra en un laboratorio por lo cual no se puede agregar a este");
            }
        } else {
            JOptionPane.showMessageDialog(null, "No se puede agregar debido a que solo se reliza registro de ingreso de estudiantes y no de docentes");
        }
        cargarTablaEstudiante();
        jLabelNombreEstudianteEspera.setText(estudiantesEnCola());
        cupoMaximo();
    }//GEN-LAST:event_btnIngresarEstudianteMouseClicked

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        ventanaLaboratorio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverMouseClicked

    public String estudiantesEnCola() {
        if (controladorVentanaAdministradorLaboratorio.obtenerLaboratorio(fila, columna).getCola().getCabeza() != null) {
            return controladorVentanaAdministradorLaboratorio.obtenerLaboratorio(fila, columna).obtenerDatoCola().getNombre();
        }
        return "Ninguno";
    }

    public void cupoMaximo() {
        jLabelCupoMaximo.setText(laboratorio.getCupo() + "/ " + cupoLaboratorio());
    }

    private void btnEliminarIngresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarIngresoMouseClicked
        if (txtCodigoUniversitario.equals("Codigo univeristario") || txtCodigoUniversitario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecciona/escribe el codigo universitario"
                    + "del estudiante que deseas eliminar.");
        } else {
            Persona persona = controladorVentanaAdministradorLaboratorio.buscarPersonaCodigo(txtCodigoUniversitario.getText());
            Estudiante estudiante = (Estudiante) persona;
            if (estudiante != null) {
                controladorVentanaAdministradorLaboratorio.eliminarIngresoLaboratorio(estudiante.getCodigoUniversitario(), fila, columna);
                cargarTablaEstudiante();
                JOptionPane.showMessageDialog(null, "El estudiante se elimino correctamente.");
                jLabelNombreEstudianteEspera.setText(estudiantesEnCola());
                cupoMaximo();
            } else {
                JOptionPane.showMessageDialog(null, "El estudiante no se pudo eliminar.");
            }
        }
    }//GEN-LAST:event_btnEliminarIngresoMouseClicked

    private void btnPrestarHerramientasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestarHerramientasMouseClicked
        if (txtCodigoUniversitario.getText().equals("Codigo Universitario")
                || txtCodigoUniversitario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecciona el estudiante al que deseas prestar"
                    + "la herramientas");
        } else {
            String codigo = txtCodigoUniversitario.getText();
            Persona persona = controladorVentanaAdministradorLaboratorio.buscarPersonaCodigoLab(codigo, fila, columna);
            if (persona != null) {
                Estudiante estudiante = (Estudiante) persona;
                VentanaRealizarPrestamo ventanaRealizarPrestamo = new VentanaRealizarPrestamo(this, estudiante, fila, columna);
                ventanaRealizarPrestamo.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "el estudiante no se encuentra dentro de laboratorio");
            }
        }
    }//GEN-LAST:event_btnPrestarHerramientasMouseClicked

    private void TablaEstudiantesEnLaboratorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaEstudiantesEnLaboratorioMouseClicked
        String codigoUniversitario = String.valueOf(TablaEstudiantesEnLaboratorio.getModel().getValueAt(TablaEstudiantesEnLaboratorio.getSelectedRow(), 0));
        txtCodigoUniversitario.setText(codigoUniversitario);
    }//GEN-LAST:event_TablaEstudiantesEnLaboratorioMouseClicked

    private void btnRetirarEstudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetirarEstudiantesMouseClicked
        controladorVentanaAdministradorLaboratorio.eliminarTodosLosEstudiante(fila, columna);
        cargarTablaEstudiante();
        cupoMaximo();
        jLabelNombreEstudianteEspera.setText(estudiantesEnCola());
    }//GEN-LAST:event_btnRetirarEstudiantesMouseClicked

    private void btnVolver1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolver1MouseClicked
        controladorVentanaAdministradorLaboratorio.eliminarTodosLosEstudianteEnCola(fila, columna);
        jLabelNombreEstudianteEspera.setText(estudiantesEnCola());
    }//GEN-LAST:event_btnVolver1MouseClicked

    private void btnRetirarEstudiantes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRetirarEstudiantes1MouseClicked
        controladorVentanaAdministradorLaboratorio.retirarTodasHerramientas(fila, columna);
        JOptionPane.showMessageDialog(null, "Se retiraron todas las herramientas del laboratorio");
    }//GEN-LAST:event_btnRetirarEstudiantes1MouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaEstu;
    private javax.swing.JTable TablaEstudiantesEnLaboratorio;
    private javax.swing.JLabel btnDeshabilitarLaboratorio;
    private javax.swing.JLabel btnEliminarIngreso;
    private javax.swing.JLabel btnIngresarEstudiante;
    private javax.swing.JLabel btnPrestarHerramientas;
    private javax.swing.JLabel btnRetirarEstudiantes;
    private javax.swing.JLabel btnRetirarEstudiantes1;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JLabel btnVolver1;
    private javax.swing.JPanel jDeshabilitarLaboratorio;
    private javax.swing.JPanel jEliminarIngreso;
    private javax.swing.JPanel jIngresarEstudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelCupoMaximo;
    private javax.swing.JLabel jLabelNombreEstudianteEspera;
    private javax.swing.JLabel jLabelTextEstudianteCola;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPrestarHerramientas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel jVolver;
    private javax.swing.JPanel jVolver1;
    private javax.swing.JPanel jVolver2;
    private javax.swing.JPanel jVolver3;
    private javax.swing.JTextField txtCodigoUniversitario;
    // End of variables declaration//GEN-END:variables
}
