package Vistas;

import controladores.ControladorVentanaAdministradorLaboratorio;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import src.Herramienta;
import src.Universidad;

public class VentanaGestionarHerramienta extends javax.swing.JFrame {

    private ControladorVentanaAdministradorLaboratorio controladorVentanaAdministradorLaboratorio;
    private VentanaAdministradorLaboratorio ventanaLaboratorio;
    private VentanaLogin ventanaPrincipal;

    public VentanaGestionarHerramienta(VentanaAdministradorLaboratorio ventanaLaboratorio) {
        initComponents();
        this.controladorVentanaAdministradorLaboratorio = new ControladorVentanaAdministradorLaboratorio();
        this.ventanaLaboratorio = ventanaLaboratorio;
        txtCodigoHerramienta.setEnabled(false);
        setLocationRelativeTo(this);
        cargarTablaHerramienta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNombreHerramienta = new javax.swing.JTextField();
        txtCodigoHerramienta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHerramientas = new javax.swing.JTable();
        jRegstrar = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JLabel();
        jEliminar = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JLabel();
        jVolver = new javax.swing.JPanel();
        btnVolver = new javax.swing.JLabel();
        jSeparatorNombreHerramienta = new javax.swing.JSeparator();
        jSeparatorCodigoHerramienta = new javax.swing.JSeparator();
        jLabelTextHerramientasRegistradas = new javax.swing.JLabel();
        jLabelTextGetionarHerramientas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtNombreHerramienta.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtNombreHerramienta.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreHerramienta.setText("Nombre herramienta");
        txtNombreHerramienta.setBorder(null);
        txtNombreHerramienta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreHerramientaMousePressed(evt);
            }
        });

        txtCodigoHerramienta.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        txtCodigoHerramienta.setForeground(new java.awt.Color(153, 153, 153));
        txtCodigoHerramienta.setText("Codigo Herramienta");
        txtCodigoHerramienta.setBorder(null);

        tablaHerramientas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaHerramientasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaHerramientas);

        jRegstrar.setBackground(new java.awt.Color(51, 102, 255));

        btnRegistrar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setToolTipText("");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jRegstrarLayout = new javax.swing.GroupLayout(jRegstrar);
        jRegstrar.setLayout(jRegstrarLayout);
        jRegstrarLayout.setHorizontalGroup(
            jRegstrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jRegstrarLayout.setVerticalGroup(
            jRegstrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jEliminar.setBackground(new java.awt.Color(51, 102, 255));

        btnEliminar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setToolTipText("");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jEliminarLayout = new javax.swing.GroupLayout(jEliminar);
        jEliminar.setLayout(jEliminarLayout);
        jEliminarLayout.setHorizontalGroup(
            jEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );
        jEliminarLayout.setVerticalGroup(
            jEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jVolver.setBackground(new java.awt.Color(51, 102, 255));

        btnVolver.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolver.setText("VOLVER");
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jVolverLayout = new javax.swing.GroupLayout(jVolver);
        jVolver.setLayout(jVolverLayout);
        jVolverLayout.setHorizontalGroup(
            jVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jVolverLayout.setVerticalGroup(
            jVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabelTextHerramientasRegistradas.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabelTextHerramientasRegistradas.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTextHerramientasRegistradas.setText("Herramientas registradas:");

        jLabelTextGetionarHerramientas.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabelTextGetionarHerramientas.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTextGetionarHerramientas.setText("GESTIONAR HERRAMIENTAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTextHerramientasRegistradas)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jVolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRegstrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCodigoHerramienta)
                                .addComponent(jSeparatorCodigoHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombreHerramienta)
                                .addComponent(jSeparatorNombreHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelTextGetionarHerramientas, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTextGetionarHerramientas)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNombreHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparatorNombreHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCodigoHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparatorCodigoHerramienta, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(jRegstrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTextHerramientasRegistradas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverMouseClicked
        ventanaLaboratorio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverMouseClicked

    public void cargarTablaHerramienta() {
        DefaultTableModel model = new DefaultTableModel();
        String[] columnas = new String[]{
            "Codigo herramienta", "nombre", "Disponibilidad"
        };
        model.setColumnIdentifiers(columnas);
        for (int i = 0; i < controladorVentanaAdministradorLaboratorio.getHerramientas().getSize(); i++) {
            model.addRow(new Object[]{
                controladorVentanaAdministradorLaboratorio.getHerramientas().obtenerDatoIndice(i).getCodigoHerramienta(),
                controladorVentanaAdministradorLaboratorio.getHerramientas().obtenerDatoIndice(i).getNombre(),
                controladorVentanaAdministradorLaboratorio.getHerramientas().obtenerDatoIndice(i).getDisponibilidad(),});
        }
        tablaHerramientas.setModel(model);
    }

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        if (txtNombreHerramienta.getText().equals("Nombre herramienta")) {
            JOptionPane.showMessageDialog(null, "Por favor rellena los datos");
        } else {
            int auxCodigoHerramienta = Universidad.codigoHerramienta;
            String codigoHerramienta = "herramienta" + auxCodigoHerramienta;
            String nombreHerramienta = txtNombreHerramienta.getText();
            Herramienta herramienta = new Herramienta(nombreHerramienta, codigoHerramienta);
            if (controladorVentanaAdministradorLaboratorio.registrarHerramienta(herramienta)) {
                JOptionPane.showMessageDialog(null, "se registro correctamente la herramienta: " + herramienta.getNombre());
                txtNombreHerramienta.setText("Nombre herramienta");
                txtNombreHerramienta.setForeground(Color.gray);
                txtCodigoHerramienta.setText("Codigo herramienta");
                txtCodigoHerramienta.setForeground(Color.gray);
            } else {
                JOptionPane.showMessageDialog(null, "Ya se encuentra registrada la maxima cantidad de herramienta de ese tipo: " + herramienta.getNombre()
                        + " por lo cual no puedes registrar mas");
                txtNombreHerramienta.setText("Nombre herramienta");
                txtNombreHerramienta.setForeground(Color.gray);
                txtCodigoHerramienta.setText("Codigo herramienta");
                txtCodigoHerramienta.setForeground(Color.gray);
            }
            cargarTablaHerramienta();
        }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void txtNombreHerramientaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreHerramientaMousePressed
        if (txtNombreHerramienta.getText().equals("Nombre herramienta")) {
            txtNombreHerramienta.setText("");
            txtNombreHerramienta.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNombreHerramientaMousePressed

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        if (txtNombreHerramienta.getText().equals("Nombre herramienta") || txtCodigoHerramienta.getText().equals("Codigo herramienta")) {
            JOptionPane.showMessageDialog(null, "Por favor selecciona/ la herramienta a eliminar");
            txtNombreHerramienta.setText("Nombre herramienta");
            txtNombreHerramienta.setForeground(Color.gray);
            txtCodigoHerramienta.setText("Codigo herramienta");
            txtCodigoHerramienta.setForeground(Color.gray);
        } else {
            String codigoHerramienta = txtCodigoHerramienta.getText();
            if (controladorVentanaAdministradorLaboratorio.eliminarHerramienta(codigoHerramienta)) {
                JOptionPane.showMessageDialog(null, "La herramienta con el codigo: " + codigoHerramienta + " fue eliminado correctamente");
                txtNombreHerramienta.setText("Nombre herramienta");
                txtNombreHerramienta.setForeground(Color.gray);
                txtCodigoHerramienta.setText("Codigo herramienta");
                txtCodigoHerramienta.setForeground(Color.gray);
            } else {
                JOptionPane.showMessageDialog(null, "La herramienta con el codigo: " + codigoHerramienta + " no pudo ser elimnado");
                txtNombreHerramienta.setText("Nombre herramienta");
                txtNombreHerramienta.setForeground(Color.gray);
                txtCodigoHerramienta.setText("Codigo herramienta");
                txtCodigoHerramienta.setForeground(Color.gray);
            }
            cargarTablaHerramienta();
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void tablaHerramientasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaHerramientasMouseClicked
        int seleccion = tablaHerramientas.rowAtPoint(evt.getPoint());
        String codigoHerramienta = tablaHerramientas.getValueAt(seleccion, 0).toString();
        String nombreHerramienta = tablaHerramientas.getValueAt(seleccion, 1).toString();
        txtCodigoHerramienta.setText(codigoHerramienta);
        txtNombreHerramienta.setText(nombreHerramienta);
    }//GEN-LAST:event_tablaHerramientasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JLabel btnRegistrar;
    private javax.swing.JLabel btnVolver;
    private javax.swing.JPanel jEliminar;
    private javax.swing.JLabel jLabelTextGetionarHerramientas;
    private javax.swing.JLabel jLabelTextHerramientasRegistradas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jRegstrar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparatorCodigoHerramienta;
    private javax.swing.JSeparator jSeparatorNombreHerramienta;
    private javax.swing.JPanel jVolver;
    private javax.swing.JTable tablaHerramientas;
    private javax.swing.JTextField txtCodigoHerramienta;
    private javax.swing.JTextField txtNombreHerramienta;
    // End of variables declaration//GEN-END:variables
}
